#!/usr/bin/env python3
"""
Build a 1M-document raw Hindi corpus for continued pre-training.

Why raw text and not 1M instruction pairs:
  * IndicCorpV2 `hi` is 80 GB of monolingual Hindi in 3 files. 1M documents is a
    download budget question, not a data availability question.
  * CPT is the stage that measurably worked. Devanagari went 0/5 -> 5/5 when
    Hindi Wikipedia went through it. The failure that remains is register, and
    volume of machine-translated instruction text does not fix register - our
    own history proves it: 5,500 -> 8,500 rows moved nothing.
  * A 1M SFT set generated by the teacher would take 255 days at the measured
    22 s/answer. Not a scheduling problem.

Streams IndicCorpV2 rather than downloading 80 GB, writes newline-delimited JSON,
resumable by document count, and filters on the way through.
"""
import json, os, re, sys, time, urllib.request, hashlib

OUT       = sys.argv[1] if len(sys.argv) > 1 else "/home/ubuntu/hindi-finetune/cpt_hindi_1m.jsonl"
TARGET    = int(sys.argv[2]) if len(sys.argv) > 2 else 1_000_000
MIN_WORDS = 40          # below this a "document" is a fragment or a nav stub
MAX_WORDS = 1200        # keeps a single row inside a sane context window
IC_FILES  = ["data/hi-1.txt", "data/hi-2.txt", "data/hi-3.txt"]
IC_BASE   = "https://huggingface.co/datasets/ai4bharat/IndicCorpV2/resolve/main/"

DEV   = re.compile(r"[\u0900-\u097F]")
# Devanagari is byte-level in this tokenizer at 1.31 tok/char, so cap on CHARS too
MAX_CHARS = 4000
LATIN = re.compile(r"[A-Za-z]")

def frac_dev(s):
    return sum(1 for c in s if "\u0900" <= c <= "\u097F") / max(1, len(s))

def keep(text):
    w = len(text.split())
    if w < MIN_WORDS or w > MAX_WORDS:      return False
    if len(text) > MAX_CHARS:               return False
    if frac_dev(text) < 0.55:               return False   # mostly English/Latin
    letters = [c for c in text if c.isalpha()]
    if letters and sum(1 for c in letters if LATIN.match(c)) / len(letters) > 0.45:
        return False                                        # code / transliterated soup
    return True

def stream(fn, chunk=1 << 22):
    """Yield lines from a remote text file without downloading the whole thing."""
    url = IC_BASE + fn
    req = urllib.request.Request(url, headers={"User-Agent": "cpt-builder/1.0"})
    with urllib.request.urlopen(req, timeout=900) as r:
        buf = b""
        while True:
            b = r.read(chunk)
            if not b:
                if buf: yield buf.decode("utf-8", "replace")
                return
            buf += b
            *lines, buf = buf.split(b"\n")
            for ln in lines:
                yield ln.decode("utf-8", "replace")

def already_done(path):
    n = 0
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            for _ in f: n += 1
    return n

def main():
    n0 = already_done(OUT)
    if n0 >= TARGET:
        print(f"already has {n0:,} rows, nothing to do"); return
    print(f"target {TARGET:,}   resuming from {n0:,}   -> {OUT}")
    t0 = time.time(); n = n0; seen = 0; stat = {"kept": 0, "short": 0, "long": 0,
                                                "latin": 0, "chars": 0, "empty": 0}
    with open(OUT, "a", encoding="utf-8") as out:
        for fn in IC_FILES:
            if n >= TARGET: break
            print(f"\nstreaming {fn} ...", flush=True)
            try:
                for line in stream(fn):
                    seen += 1
                    t = line.strip()
                    if not t:
                        stat["empty"] += 1; continue
                    w = len(t.split())
                    if w < MIN_WORDS:  stat["short"] += 1; continue
                    if w > MAX_WORDS:  stat["long"]  += 1; continue
                    if len(t) > MAX_CHARS: stat["chars"] += 1; continue
                    if not keep(t):    stat["latin"] += 1; continue
                    out.write(json.dumps({
                        "text": t,
                        "src": "indiccorpv2",
                        "key": hashlib.sha1(t[:200].encode()).hexdigest()[:16],
                    }, ensure_ascii=False) + "\n")
                    n += 1; stat["kept"] += 1
                    if n % 20_000 == 0:
                        out.flush()
                        el = time.time() - t0
                        print(f"  {n:>9,} / {TARGET:,}   {seen:>10,} scanned   "
                              f"{el/60:.1f}m   {(n-n0)/max(1,el):.0f} docs/s   "
                              f"keep {stat['kept']/max(1,seen):.1%}", flush=True)
                    if n >= TARGET: break
            except Exception as e:
                print(f"  stream ended early: {type(e).__name__}: {e}", flush=True)
                break
            out.flush()
    el = time.time() - t0
    print(f"\ndone: {n:,} rows in {el/60:.1f} min")
    print(f"scanned {seen:,}   kept {stat['kept']:,}   keep-rate {stat['kept']/max(1,seen):.1%}")
    print(f"rejected: {stat}")

if __name__ == "__main__":
    main()
