#!/usr/bin/env python3
"""Build teach/prompts_v8.jsonl: every topic we have, plus the register v7 never had.

Why this exists. v7 shipped 57,687 rows measured like this: response length p10/median/p90
= 40/47/52 words, ZERO rows under 15 words, instruction median 13 words, 291 (0.50%)
chitchat rows, 1 multi-turn row. So the model has exactly one speech act - a 47-word
topical answer to a 13-word question - and "kaise ho bhai" gets stretched into a topic and
answered with evasive boilerplate. That is a distribution problem, not a volume problem:
11.9k -> 19.8k -> 57.7k rows all had the same shape, which is why every release sounded
more fluent and still wrong.

Two inputs:
  1. topical: dedupe every teach/*.jsonl pool (measured 117,333 unique instructions across
     13 categories, 1,019 subjects in expand_pool5). Breadth is already paid for; it just
     was never released into v7.
  2. chat: the missing register, generated by the teacher from ~120 social scenes -
     greetings, identity, thanks, small commands, follow-ups, corrections, feelings.
     Marked reg="chat" so generate.py weights them short.

  python3 teach/build_prompts_v8.py            # writes teach/prompts_v8.jsonl
"""
import concurrent.futures as cf
import glob, hashlib, json, os, re, sys, threading, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from teacher_cfg import TEACHER          # gitignored: baseUrl / apiKey / model
BASE, KEY, MODEL = TEACHER["baseUrl"], TEACHER["apiKey"], TEACHER["model"]

OUT = os.path.join(HERE, "prompts_v8.jsonl")
N_CHAT_CALLS = int(sys.argv[1]) if len(sys.argv) > 1 else 2500  # ~5.8 kept/call -> ~14k prompts
CONC = 16

DEV = lambda s: sum(1 for c in s if "ऀ" <= c <= "ॿ") / max(1, len(s))

# ---------------------------------------------------------------- 1. topical, from pools
# pool_master/extra_prompts5 carry the widest subject coverage; the release files are
# answers, not prompts, and are skipped. `adaption` is excluded outright: it is the
# machine-translated pool that contributed 1,245/1,245 Marathi rows to v6 (FINDINGS 13).
SKIP_SOURCES = {"adaption"}
def topical():
    seen, rows = set(), []
    for p in sorted(glob.glob(os.path.join(HERE, "*.jsonl"))):
        base = os.path.basename(p)
        if base.startswith(("teacher_gen", "train_v1", "prompts_v8")):
            continue
        for line in open(p, encoding="utf-8"):
            try: r = json.loads(line)
            except Exception: continue
            if r.get("src") in SKIP_SOURCES: continue
            plang = r.get("plang", "hi")
            # Product scope is Hindi + Hinglish only. 5,370 `en` prompts in the pools would
            # each cost a generation call to produce an English target row we then drop.
            if plang in ("en", "en_en"): continue
            i = (r.get("instruction") or "").strip()
            if len(i) < 8: continue
            k = i.lower()
            if k in seen: continue
            seen.add(k)
            rows.append({"key": hashlib.sha1(i.encode()).hexdigest()[:16],
                         "instruction": i, "plang": plang,
                         "src": r.get("src", "pool"), "reg": "topical",
                         "topic": r.get("category") or r.get("src") or ""})
    return rows

# ---------------------------------------------------------------- 2. the chat register
SCENES = [
 "greeting a friend on chat", "asking how someone is doing", "thanking someone warmly",
 "a small apology", "asking what the assistant can do", "asking who the assistant is",
 "greeting in the morning", "greeting at night", "casual 'what's up'", "asking about family",
 "asking about someone's day", "reacting to good news", "reacting to bad news",
 "console someone", "cheering someone up", "asking for a short answer", "saying 'batao na'",
 "asking to repeat", "asking 'phir?'", "asking 'aur kya?'", "disagreeing politely",
 "saying that is wrong", "asking to speak in Hindi", "asking to speak simply",
 "asking to be shorter", "asking to explain again", "saying 'theek hai'", "saying 'chhodo'",
 "small talk about weather", "small talk about traffic", "small talk about food at home",
 "asking if someone is free", "saying you are bored", "saying you are tired",
 "saying you are happy", "asking for a joke", "asking for good news", "asking about cricket",
 "asking about a movie", "asking about a festival", "asking about weekend plans",
 "greeting an elder respectfully", "talking to a younger sibling", "chat with a colleague",
]
CHAT_SYS = (
 "You are writing FAKE user messages for a Hindi / Hinglish chat assistant to learn from. "
 "You are NOT answering them. Output 15 short casual user messages for the given scene.\n"
 "SCRIPT RULE - this is mandatory: messages 1 to 8 in PURE DEVANAGARI HINDI script "
 "(जैसे: कैसे हो भाई? आज खाने में क्या बनाया?), messages 9 to 15 in ROMANIZED Hinglish "
 "(jaise: kaise ho bhai? aaj khane mein kya banaya?). Never mix scripts inside one message.\n"
 "Other rules: one message per line, no numbering, no bullets, no explanations, under 12 "
 "words each and most under 8. Everyday spoken words. Do NOT write prompts that need a "
 "40-word factual essay; these are conversational openers. Make all 15 different.")

def call(user, sys_p, max_tokens=1200, temp=0.9):
    body = json.dumps({"model": MODEL, "temperature": temp, "max_tokens": max_tokens,
                       "messages": [{"role": "system", "content": sys_p},
                                    {"role": "user", "content": user}]}).encode()
    req = urllib.request.Request(BASE + "/chat/completions", data=body,
                                 headers={"Authorization": f"Bearer {KEY}",
                                          "Content-Type": "application/json"})
    import time
    for a in range(3):
        try:
            with urllib.request.urlopen(req, timeout=180) as resp:
                j = json.load(resp)
            c = (j["choices"][0]["message"]["content"] or "").strip()
            if c: return c
        except Exception:
            pass
        time.sleep(2 * (a + 1))
    return ""

def one_chat(seed):
    scene = SCENES[seed % len(SCENES)]
    out = call(f"Scene: {scene}\nVariant: {seed // len(SCENES) + 1}", CHAT_SYS)
    rows = []
    for ln in out.splitlines():
        i = re.sub(r"^[\s\-*•\d.)]+", "", ln).strip().strip('"')
        w = len(i.split())
        if not (2 <= w <= 14): continue
        d = DEV(i)
        # Script band. The earlier filter `0.08 < d < 0.92` REJECTED pure Devanagari (d~1.0)
        # and silently threw away every Hindi row, which is how the first draft came back
        # 100% romanized. Keep pure scripts, drop only genuinely half-and-half lines.
        if d >= 0.50:   plang = "hi"
        elif d <= 0.05: plang = "hinglish"
        else: continue
        rows.append({"key": hashlib.sha1(i.lower().encode()).hexdigest()[:16],
                     "instruction": i, "plang": plang,
                     "src": "chat_synth", "reg": "chat", "topic": f"chat:{scene}"})
    return rows

def build_chat():
    print(f"generating chat-register prompts: {N_CHAT_CALLS} calls at conc {CONC}", flush=True)
    rows, seen = [], set()
    lock = threading.Lock()
    with cf.ThreadPoolExecutor(max_workers=CONC) as ex:
        for n, got in enumerate(ex.map(one_chat, range(N_CHAT_CALLS))):
            with lock:
                for r in got:
                    if r["key"] not in seen:
                        seen.add(r["key"]); rows.append(r)
            if (n + 1) % 100 == 0:
                print(f"  {n+1}/{N_CHAT_CALLS} calls -> {len(rows):,} unique chat prompts", flush=True)
    return rows

if __name__ == "__main__":
    top = topical()
    chat = build_chat()
    seen = {r["key"] for r in chat}
    top = [r for r in top if r["key"] not in seen]
    # chat first: if the background generation is stopped early, the missing register is
    # already in the file rather than the last 30% of yet another topical answer.
    with open(OUT, "w", encoding="utf-8") as f:
        for r in chat + top:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(f"\nwrote {OUT}: {len(chat)+len(top):,} prompts "
          f"({len(chat):,} chat + {len(top):,} topical)")
    print(f"chat scripts: hi {sum(1 for r in chat if r['plang']=='hi'):,} "
          f"hinglish {sum(1 for r in chat if r['plang']=='hinglish'):,}")
    print("next: nohup python3 teach/generate.py 60000 16 >> /tmp/gen_v8.log 2>&1 &")
